pact-foundation/pact-broker-docker

README.md
Add heartbeat path to the readme so developers don't have to go digging in the code to find it.
=> Add heatbeat path to readme

Dockerfile
Should we peg to `ruby:2.6.4-alpine` instead of `ruby:2.6-alpine`?
=> chore: remove busybox 1.30 - already installed on alpine 3.10

docker-compose.yml
**Description** :
Typically we don't have to clean up Postgres data whenever we bring down the Postgres service in general unless there is a different use-case we want to achieve.
- What are we changing here? 
Updating Docker compose to use volumes for Postgres so that every time we bring back the docker services we use the existing volume on the system.
```
Logs will look like below
pact_broker_1  | Puma starting in single mode...
pact_broker_1  | * Version 3.12.2 (ruby 2.6.4-p104), codename: Llamas in Pajamas
pact_broker_1  | * Min threads: 0, max threads: 16
postgres_1     |
postgres_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1     |
pact_broker_1  | * Environment: production
```
=> Update docker-compose to persist postgres data

.dockerignore, .gitignore, pact_broker/config.ru, pact_broker/database_connection.rb, pact_broker/docker_configuration.rb, spec/docker_configuration_spec.rb
I would like to run pact broker on Heroku.  Although this can be done with the existing image, Heroku routinely rotates database credentials, which then will invalidate the static `PACT_BROKER_*` environment variable settings.
Add support for configuring the container with a URL, rather than solely the series of `PACT_BROKER_*` environment variable parts.
An additional challenge: Heroku's configuration mechanism does not allow one to alias a config var; for this to work, the URL needs to be pulled from `DATABASE_URL`.  This gave rise to a URL provider configuration: one can set the provider (`PACT_BROKER_DATABASE_URL_PROVIDER`) to a string, which should be the name of the environment variable that contains the actual URL, maintaining the `PACT_BROKER_*` convention.
- Refactors …
=> Add PACT_BROKER_DATABASE_URL support

pact_broker/Gemfile, pact_broker/Gemfile.lock
Upgrade to latest puma version. Amongst the other it extends the maximum path length from 2k to 8k, which let us use custom (base64 encoded data) as version names.
=> feat(deps): Update puma to 5.3.1

Dockerfile-bundle-base, Dockerfile-package-base, Gemfile.lock, pact_broker/Gemfile.lock
Fix security issues described in [issue #93](https://github.com/pact-foundation/pact-broker-docker/issues/93).
=> Issue #93: Upgrade Bundler to version 2.2.33 to fix security issues.

Dockerfile
Fix security issues described in [issue #88](https://github.com/pact-foundation/pact-broker-docker/issues/88).
=> Issue #88: Upgrade Supercronic to version 0.2.1 to fix security issues.

.github/workflows/test.yml
PR builds from contributors fail because they don't have access to secrets to login to the docker repository.
Not sure why this step is needed, as we test from the image built in the CI run, and don't push it as part of this job.
Maybe its due to docker licensing restrictions? 🤷🏾‍♂️ 
It also stops dependency update builds from running the test step, which causes more headache for maintainers, example PR actions run 
https://github.com/pact-foundation/pact-broker-docker/actions/runs/4675302277/jobs/8280283767#step:6:9
=> chore(dev-ex): remove docker login step from test run

.github/workflows/audit.yml, script/release-workflow/audit.sh
Run the trivy audit as a cron job, so that we get alerted to issues, rather than only being run at release time
Current error when running trivy against a built image 
https://github.com/YOU54F/pact-broker-docker/actions/runs/4735726395/jobs/8406325952
```
aquasecurity/trivy info checking GitHub for latest tag
aquasecurity/trivy info found version: 0.40.0 for v0.40.0/Linux/64bit
aquasecurity/trivy info installed /usr/local/bin/trivy
2023-04-18T18:28:08.143Z	INFO	Need to update DB
2023-04-18T18:28:08.143Z	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2023-04-18T18:28:08.143Z	INFO	Downloading DB...
2023-04-18T18:28:10.786Z	INFO	Vulnerability scanning is enabled
2023-04-18T18:28:10.786Z	INFO	Secret scanning is enabled
2023-04-18T18:28:10.786Z	INFO	If your scanning is slow, please try …
```
=> ci(dev-ex): run trivy audit as cron job so no release surpises

.github/workflows/audit.yml, .github/workflows/test.yml, Dockerfile, README.md, script/release-workflow/docker-build.sh, script/release-workflow/docker-push.sh, script/release-workflow/docker-scan.sh, script/release-workflow/run.sh, script/release-workflow/set-env-vars.sh, script/scan.sh, script/test.sh, test/Dockerfile
closes #30 
create and publish arm64 + arm versions of pact cli and pact broker docker images for use in raspberry Pi's / mac m1/2 etc.
currently publishing to personal docker hub acc for testing
- https://hub.docker.com/r/you54f/pact-broker
Related
- https://github.com/pact-foundation/pact-ruby-cli/issues/51
- https://hub.docker.com/r/you54f/pact-cli
- https://github.com/pact-foundation/pact-ruby-cli/pull/98
Have spun up the images briefly but would warrant some decent testing
Have spun up the images briefly on an m1 pro macbook but would warrant some decent testing - I have several pi's (3b+ and 4) so will give them a whirl
Fancy giving it a test, try `docker pull you54f/pact-broker` and let us know how you get on it the thread.
I have tested now across 32 bit rasp pi / arm64 macos + …
=> Multi manifest build - arm64/arm (new) + amd64 (current)

.github/workflows/audit.yml
due to missing binaries 
https://github.com/aquasecurity/trivy/discussions/4972
=> ci(audit): remove audit step for armv7

Dockerfile
Update SuperCronic to 0.2.27 to ensure updated version of GO.
This should get rid of vulnerabilities in older GO versions.
Updated the version and the SHA's according to this page 
https://github.com/aptible/supercronic/releases/tag/v0.2.27
`CMD ["config.ru"]` on line 77 is copied from the chore/deps/supercronic/v0.2.26
=> update superCronic to 0.2.27

Dockerfile
Upgrades base image to ruby:3.2.3-alpine3.19
Upgrades SuperCronic to ver 0.2.29
Both these upgrades resolves a set of open CVE:s with severity ranging from Critical to Medium. The most important one being described in issue #161 .
Tested by local build of Docker image and test using docker-compose.yml modified to use the locally built image.
=> Issue 161 upgrades to resolve open CVE:s

pact_broker/Gemfile
=> fix: force_ruby_platform for sqlite gem to build natively

.github/workflows/release_image.yml, README.md, script/release-workflow/docker-push.sh
Publish images to ghcr.io as well as docker.io
- [main tracking ticket](https://github.com/pact-foundation/devrel/issues/29)
- [pact-ruby-cli PR](https://github.com/pact-foundation/pact-ruby-cli/pull/127)
Note. includes #171 so we aren't publishing the `-multi` suffixed images to ghcr
=> feat: Docker/publish to ghcr

script/release-workflow/docker-push.sh
GitHub container registries must contain a matching NAMESPACE to the GitHub user or org.
This worked on my personal fork, as my GH and Docker username are the same, however pact-foundation uses a hyphen-less NAMESPACE when publishing to docker.io
https://hub.docker.com/u/pactfoundation
We therefore need to set the org name to pact-foundation when publishing to ghcr.
=> fix: ghcr images need to publish to pact-foundation / dockerhub images to pactfoundation

pact_broker/config/puma.rb, script/test.sh
Reverts pact-foundation/pact-broker-docker#170
Re: failing build
https://github.com/pact-foundation/pact-python/pull/578
Relates to comments noted during thisPR
https://github.com/pact-foundation/pact-broker-docker/pull/173#issue-2154393809
It seems we might need to dig into this a bit further to understand why we are seeing intermittent failures before rolling this out, as they are cropping up in consuming projects
=> Revert "feat: bind to IPv6 'any' as well as IPv4 'any'"

script/release-workflow/docker-push.sh
These annotations are useful for tools (such as Renovate and Snyk) to use as well as for manual use by individuals.
For example, [Snyk uses them in its UI](https://snyk.io/blog/how-and-when-to-use-docker-labels-oci-container-annotations/) and [Renovate uses them to find release notes](https://github.com/renovatebot/renovate/blob/34.115.1/lib/modules/datasource/docker/readme.md).
See: https://github.com/opencontainers/image-spec/blob/v1.1.0/annotations.md#pre-defined-annotation-keys
=> feat: Add OCI image annotations

README.md, example-k8s-deployment/infrastructure/deploy_cfn.sh, script/test.sh
```
ERROR: for pact-broker  'ContainerConfig'
KeyError: 'ContainerConfig'
```
Transpires `docker-compose` is deprecated. I didn't get the memo 😅 
https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2
That is why CI was 💔 instead of 💚
=> fix(ci): docker-compose possibly causing issues

README.md
DiUS pact broker image is no longer supported and is not actively maintained.
See https://github.com/pact-foundation/docs.pact.io/issues/242
=> docs: remove dius pact broker section

.github/workflows/audit.yml, .github/workflows/test.yml
Triggering on all 'push' and 'pull_request' events will result in duplicated CI runs in PRs (due to both conditions being met).
Instead, trigger only on pushes to `master`, or updates to PRs targetting `master`.
=> chore(ci): prevent duplicate ci triggers

.github/workflows/audit.yml
Arm runners now available, so may as well use them for the audit runs to speed them up
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
Need to also apply to the main publishing runs to take advantage of the native arm64 runners
=> ci: audit on ubuntu-24.04-arm runner
